export { default as HomePage } from './home'
export { default as FavouritesPage } from './favourites'
export { default as NewsLetterPage } from './newsletter'
export { default as NotFoundPage } from './not_found'
export { default as SearchResultPage } from './search_result'
